# Local secrets - never commit this file

groq.api.key=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
app.jwt.secret=talentbridge-secret-key-should-be-very-long-and-secure-at-least-256-bits
cloudinary.cloud-name=dbnfyjayn
cloudinary.api-key=481622184342483
cloudinary.api-secret=ook8RcbVd9V3o3prYmGz9aPJAJ8
spring.datasource.url=jdbc:postgresql://localhost:5432/talentbridge
spring.datasource.username=postgres
spring.datasource.password=fibrinogen0
spring.mail.password=your_mail_password